name: mobfinder
channels:
  - etetoolkit
  - bioconda
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - biopython=1.78=py312h5eee18b_0
  - blas=1.0=openblas
  - blast=2.12.0=hf3cf87c_4
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - curl=7.88.1=hdbd6064_2
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dbus=1.16.2=h5bd4931_0
  - entrez-direct=24.0=he881be0_0
  - ete3=3.1.2=pyh39e3cac_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gettext=0.21.0=h39681ba_1
  - gfortran_impl_linux-64=11.2.0=h1234567_1
  - gfortran_linux-64=11.2.0=hc2dff05_2
  - glib=2.69.1=he621ea3_2
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - harfbuzz=4.3.0=hf52aaf7_1
  - icu=58.2=he6710b0_3
  - jpeg=9f=h5ce9db8_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=h252cb56_2
  - libcurl=7.88.1=h251f7ec_2
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=hb25bd0a_1
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.20=hdbd6064_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - libzlib=1.2.13=h4ab18f5_6
  - lmdb=0.9.31=hb25bd0a_0
  - lxml=5.2.1=py312hdbbb534_0
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.2.1=h1bed415_1
  - mysql=5.7.24=h721c034_2
  - ncurses=6.5=h7934f7d_0
  - nspr=4.37=h8459abe_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.26.4=py312hc213724_1
  - numpy-base=1.26.4=py312hf387b04_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py312h06a4308_0
  - pango=1.50.7=h05da053_0
  - pcre=8.45=h295c915_0
  - pcre2=10.37=he7ceb23_1
  - perl=5.32.1=0_h5eee18b_perl5
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.103=pl5321h87f3376_0
  - perl-compress-raw-zlib=2.103=pl5321h87f3376_0
  - perl-encode=3.19=pl5321hec16e2b_1
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.106=pl5321h87f3376_0
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h9f5acd7_1
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321hec16e2b_3
  - perl-scalar-list-utils=1.62=pl5321hec16e2b_1
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - ply=3.11=py312h06a4308_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pycurl=7.45.3=py312hdbd6064_0
  - pyqt=5.15.10=py312h6a678d5_1
  - pyqt5-sip=12.13.0=py312h5eee18b_1
  - python=3.12.11=h22baa00_0
  - qt=5.15.9=h06a4308_0
  - qt-main=5.15.2=h7358343_9
  - qt-webengine=5.15.9=h9ab4d14_7
  - r-base=4.2.0=h1ae530e_0
  - r-randomforest=4.7_1.1=r42h640688f_0
  - readline=8.3=hc2a1206_0
  - scipy=1.16.2=py312ha592af2_0
  - setuptools=78.1.1=py312h06a4308_0
  - sip=6.7.12=py312h6a678d5_1
  - six=1.17.0=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.15=h54e0aa7_0
  - tktable=2.10=hfce700a_2
  - tzdata=2025b=h04d1e81_0
  - wget=1.21.4=h251f7ec_1
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
prefix: /tools/fengtao/anaconda3/envs/mobfinder
